#!/bin/sh

if [ $# -ne 0 ]
then
  echo "Subnet provided $1"
  subnet=$1
else
  subnet=192.168.1
fi
printf "\nPinging network $subnet.1-$subnet.254\n\n"

for addr in $(seq 1 254)
do
( ping -c 1 -t 3 $subnet.$addr > /dev/null 2>&1 && echo - Ping reply: $subnet.$addr  ) &
done
sleep 2
printf "\n"
