#!/usr/bin/env python

import argparse
from bs4 import BeautifulSoup
import urllib2

parser = argparse.ArgumentParser()
parser.add_argument("url", help="enter argumenthere")
args=parser.parse_args()

url = "http://www.google.com/"
url=args.url
html_doc = urllib2.urlopen(url)
#with open("e") as f:
#  html_doc=f.read()

soup = BeautifulSoup(html_doc, 'html.parser')
#soup = BeautifulSoup(html_doc , "lxml")

print(soup.prettify())
